### ISSUE TITLE
前端项目npm install的时候出现问题

### ISSUE THREAD

**Issue by 1051556543** [lenve/VBlog#30]
前端项目npm install的时候出现问题

**Comment by panyongkang** [comment]
解决了吗？我也是npm install的时候报错，好像是版本依赖问题，但是目前无解

**Comment by fjwhp** [comment]
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (E:\workspace\active-workspace\VBlog-master\vueblog\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (E:\workspace\active-workspace\VBlog-master\vueblog\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at E:\workspace\active-workspace\VBlog-master\vueblog\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:167:21)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "E:\\workspace\\active-workspace\\VBlog-master\\vueblog\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "
--libsass_library="
gyp ERR! cwd E:\workspace\active-workspace\VBlog-master\vueblog\node_modules\node-sass
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by fjwhp** [comment]
你们也这个错吗

**Comment by huoher** [comment]
> 你们也这个错吗

是的，还找到解决方案

**Comment by huoher** [comment]
> 你们也这个错吗
@fjwhp 尝试安装python2.7试试

**Comment by newcalendar** [comment]
同是

**Comment by newcalendar** [comment]
已解决，需安装vstudio和python
