### ISSUE TITLE
登陆的账号密码可以写在README.md里

### ISSUE THREAD

**Issue by caokang** [lenve/VBlog#4]
登陆的账号密码可以写在README.md里，这样其他人跑起来也方便些。

**Comment by Spilze** [comment]
启动时报这个错：

2018-05-11 16:08:44.419 DEBUG 8772 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : Application failed to start due to an exception

org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.sang.mapper.UserMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1493) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1104) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]

**Comment by zhuchaogithub** [comment]
@Spilze 这个报错你处理了吗？我也遇到这个问题了

**Comment by zhangran2616** [comment]
@zhuchaogithub 你可以跑起来吗？我的报错了

**Comment by zhuchaogithub** [comment]
@zhangran2616 还不行

**Comment by 770679957** [comment]
eclipse设置:build path--use as source folder
再改下数据库配置,就可以了.密码都是123. 用户名数据库里随便找一个(linghu)

**Comment by YUbuntu0109** [comment]
🎨 i will be update the `README.md` file and it's will be added into `PR` :  https://github.com/lenve/VBlog/pull/44

**Comment by YUbuntu0109** [comment]
> 
> 
> 登陆的账号密码可以写在README.md里，这样其他人跑起来也方便些。

*please refer to the branch of [`newfun-restore-article-del-m`](https://github.com/YUbuntu0109/VBlog/tree/newfun-restore-article-del-m)*
